### ISSUE TITLE
Turn off for lists that don't need it

### ISSUE THREAD

**Issue by dhaligas** [k0sukey/TiISRefreshControl#1]
Is there a way to turn this off on lists that don't need it?

What would be ideal is to opt in this control on list view or table view creation

**Comment by k0sukey** [comment]
Added refreshControlEnabled property now.
Download [module](https://github.com/k0sukey/TiISRefreshControl/raw/master/be.k0suke.tiisrefreshcontrol-iphone-0.1.zip) and try this code. 

```
var tableView = Ti.UI.createTableView({
  refreshControlEnabled: false,
  data: [
    { title: 'row' }
  ]
});
```

**Comment by dhaligas** [comment]
Thank you sir!  Very awesome module!
