### ISSUE TITLE
Multiple ListView interferes with each other

### ISSUE THREAD

**Issue by sindresorhus** [k0sukey/TiISRefreshControl#3]
It seems like having multiple ListViews with TiISRefreshControl loaded at once makes them interfere with each other. This makes the second loaded window with a ListView not getting events or having any of the methods working.

I'm using the [NappDrawer](https://github.com/viezel/NappDrawer) module to have multiple windows open at once. The first one is visible if you swipe right. The refresh control works there and hides after 1s. While in the second main view it does not, and keeps spinning forever.

``` js
var NappDrawer = require('dk.napp.drawer');

function createWin() {
    var win = Ti.UI.createWindow();

    var list = Ti.UI.createListView({
        refreshControlEnabled: true
    });

    list.addEventListener('refreshstart', function () {
        console.log('list1 refreshstart');
        setTimeout(function () {
            console.log('list1 refreshstart:done');
            list.refreshFinish();
        }, 1000);
    });

    win.add(list);

    return win;
}

function createWin2() {
    var win = Ti.UI.createWindow();

    var list = Ti.UI.createListView({
        refreshControlEnabled: true
    });

    list.addEventListener('refreshstart', function () {
        console.log('list2 refreshstart');
        setTimeout(function () {
            console.log('list2 refreshstart:done');
            list.refreshFinish();
        }, 1000);
    });

    win.add(list);

    return win;
}

var win = NappDrawer.createDrawer({
    leftWindow: createWin(),
    centerWindow: createWin2(),
    closeDrawerGestureMode: NappDrawer.CLOSE_MODE_ALL,
    openDrawerGestureMode: NappDrawer.OPEN_MODE_ALL,
    leftDrawerWidth: 200
});

win.open();
```

Full runnable testcase [here](https://dl.dropboxusercontent.com/u/71884/TiISRefreshControl-testcase-3.zip).

Using https://github.com/k0sukey/TiISRefreshControl/commit/d22dbde1e536841e05cf3b9edd1db8b38442f421

**Comment by k0sukey** [comment]
I fixed. Please try again.

**Comment by sindresorhus** [comment]
Yes, that did it. Thanks for the quick fix :)
