### ISSUE TITLE
3.1.3.x refresh events

### ISSUE THREAD

**Issue by dezinezync** [k0sukey/TiISRefreshControl#4]
I built the module using 3.1.3.v20130906144623 and tried using it in my app (also uses the same SDK)

The refresh events are not fired. Works on 3.1.2.GA perfectly fine. Known issue? 

What would be a possible fix? 

I hear 3.1.3.GA releases today or tomorrow.

**Comment by dezinezync** [comment]
Ohk, this is happening when using the TiExtendView module as well. So probably something Ti changed.

**Comment by dezinezync** [comment]
```
/*if ([refreshControl isDescendantOfView:[self tableView]] == NO)
    {
        return;
    }*/
```

That seems to be conflicting with how TableViews are not included in Ti. I believe they are made the rootController, but not sure. Commenting those lines out fires the `refreshstart` and `refreshend` events. 

`tableView.refreshFinish();` still doesn't seem to do anything.

**Comment by k0sukey** [comment]
I fixed just now. Please try the latest version.

**Comment by dezinezync** [comment]
Wunderbar. Works perfectly well. Thank you.
