### ISSUE TITLE
small memory leaks ?

### ISSUE THREAD

**Issue by TiVince** [k0sukey/TiISRefreshControl#7]
self.refreshControl = [(id)[[ISRefreshControl alloc] init]  seems to create a  memory leak

autorelease seems to be needed since ISRefreshControl *refreshControl is a retain property

-(void)initializeState
{
    [super initializeState];

```
if (self)
{
    self.refreshControl = [(id)[[ISRefreshControl alloc] init] autorelease]; // autorelease needed ?
    [self.refreshControl addTarget:self
                       action:@selector(refreshStart)
             forControlEvents:UIControlEventValueChanged];
}
```

}

**Comment by k0sukey** [comment]
Thanks!
